### PR TITLE
Add Close Db Function in sqliteplugin.js and Externalstorage to android

### PR DESCRIPTION
**Pull request by Diliz**
Hi there,

I added the External storage to android:
    -1 to put dbs in sdcard/android/data/your_app/cache
    -2 to put dbs in sdcard/android/data/your_app/files

usage: var db = sqlitePlugin.openDatabase({name: db_name, externalStorage: 1});

It is named externalStorage to have the possibility to set the location for ios and externalStorage to android manually in one line.

And the close db function to close a db when you want, it can be usefull, actually I needed it cos I wanted to use androidoldimplementation on some requests, but after some requests, who don't need the androidoldimplementation to work, for example. There's many usage to a closedb function so there it is! :)

### CODE REVIEW

**Comment by Diliz** [comment]
I will add the setting "path" to opendatabase to use with create from assets, this way we will be able to get a db from where we want! :)

**Comment by brody2consult** [comment]
Thanks @Diliz for the contribution. In general I really like your changes. I am also very happy to see that you found a way to solve the problems you encountered in #361.

Unfortunately I cannot promise when I will have a chance to integrate the changes due to my current workload.

Here are my comments so far:

The external storage location should be in the `deleteDatabase` function as well. We should also add this to the test suite. I recommend that you take a look at the "delete then re-open allows subsequent queries to run" test in `spec/www/spec/legacy.js`. I can also do this myself.

I need to maintain the CoffeeScript version (I can port the Javascript changes to CoffeeScript myself).

It would be better to submit the `closedb` changes in a separate PR for consideration. I definitely understand why you need to use it but I am wondering if we can solve the problem in a different way. I will add some more details in another comment.

In general, I will integrate the changes using `git cherry-pick` instead of merging due to the branching model of this project. I highly recommend that you submit changes from a separate branch instead of your default branch to keep your default branch clean.

**Comment by brody2consult** [comment]
I think you know that the "androidLockWorkaround" simply works by closing and reopening the Android database after every COMMIT. In general I do not really like the idea of adding an extra function to the top-level API if we can avoid it. Here are a few alternatives that I can think of to solve your problem with the Android database closing mechanism:

1: If you use the `executeSql` call on the database object itself to execute a single statement, the "androidLockWorkaround" will not close and reopen the database.

2: The database object has a `readTransaction` call but it is broken and can be fixed very easily like this:

``` diff
diff --git a/SQLitePlugin.coffee.md b/SQLitePlugin.coffee.md
index 6d2d561..850fd27 100644
--- a/SQLitePlugin.coffee.md
+++ b/SQLitePlugin.coffee.md
@@ -151,7 +151,7 @@
         error newSQLError 'database not open'
         return

-      @addTransaction new SQLitePluginTransaction(this, fn, error, success, true, true)
+      @addTransaction new SQLitePluginTransaction(this, fn, error, success, false, true)
       return

     SQLitePlugin::startNextTransaction = ->
diff --git a/www/SQLitePlugin.js b/www/SQLitePlugin.js
index 4581972..9c3a879 100644
--- a/www/SQLitePlugin.js
+++ b/www/SQLitePlugin.js
@@ -122,7 +122,7 @@
       error(newSQLError('database not open'));
       return;
     }
-    this.addTransaction(new SQLitePluginTransaction(this, fn, error, success, true, true));
+    this.addTransaction(new SQLitePluginTransaction(this, fn, error, success, false, true));
   };

   SQLitePlugin.prototype.startNextTransaction = function() {
```

With this change, the BEGIN and COMMIT statements will no longer be issued and the "androidLockWorkaround" will no longer close and reopen the database in the case that you use the `readTransaction`.

I will make this fix and publish it when I get a chance.

3: You can add an "unsafe transaction" call like this:

``` diff
diff --git a/www/SQLitePlugin.js b/www/SQLitePlugin.js
index 4581972..96c4fa7 100644
--- a/www/SQLitePlugin.js
+++ b/www/SQLitePlugin.js
@@ -125,6 +125,14 @@
     this.addTransaction(new SQLitePluginTransaction(this, fn, error, success, true, true));
   };

+  SQLitePlugin.prototype.unsafeTransaction = function(fn, error, success) {
+    if (!this.openDBs[this.dbname]) {
+      error(newSQLError('database not open'));
+      return;
+    }
+    this.addTransaction(new SQLitePluginTransaction(this, fn, error, success, false, false));
+  };
+
   SQLitePlugin.prototype.startNextTransaction = function() {
     var self;
     self = this;
```

With this change, you can continue to use a similar batch transaction API but this `unsafeTransaction` call would no longer be failure-safe and the "androidLockWorkaround" will not close and reopen the database.

4: Rework the existing "androidLockWorkaround" mechanism to close and reopen the database completely within Javascript, and add an option to the `transaction` function whether or not to apply the workaround.

**Comment by Diliz** [comment]
Hi again, 

No problem, I understand for the close function, I used the androidlockworkaround, but it was not working as I expected so I added the close function, but if we can do it with the androidlockworkaround directly it can be pretty cool too, but I like to have the choice to close the db when I want without having to reopen it, dunno if I'm wrong but if i'm not the db reopen itself if we use the workaround like you told? :)

And for the externalStorage i will take a look to deletedabatase for sure, actually I just completely forgot it.

I've just added a customPath option to the forked plugin and an importPathDb option to use with createFromLocation, it will take the db where your importPathdb says it is and copy it to your customPath db, I just changed small things, tell me if you want me to add it like this, but I was looking for a better way to do it, instead of putting an importPathDb I want to put the dbpath in createFromLocation, it can be better than having 2 options, but it will add some workaround to do with other platforms as well if we call the opendatabase function, atm it is better to let an other option to set the directory from where the db you want to copy is.

No problem for the branch, I just did it in a hurry sorry ^^

**Comment by brody2consult** [comment]
> No problem, I understand for the close function, I used the
> androidlockworkaround, but it was not working as I expected so I added the
> close function, but if we can do it with the androidlockworkaround directly
> it can be pretty cool too, but I like to have the choice to close the db
> when I want without having to reopen it, dunno if I'm wrong but if i'm not
> the db reopen itself if we use the workaround like you told? :)

Now it make more sense that you don't always want to reopen the database. I
am thinking about moving the bug workaround into the JavaScript to give you
and others easier control over the behavior. When I get a chance I will
raise a pull request for discussion with you (may take 1-2 months).

> And for the externalStorage i will take a look to deletedabatase for
> sure, actually I just completely forgot it.

Thanks. We should try to get this in the test as I said before.

> I've just added a customPath option to the forked plugin and an
> importPathDb option to use with createFromLocation, it will take the db
> where your importPathdb says it is and copy it to your customPath db, I
> just changed small things, tell me if you want me to add it like this

I took a quick look and like your changes in general. But the API changes
will probably be different (see below).

> but I was looking for a better way to do it, instead of putting an
> importPathDb I want to put the dbpath in createFromLocation, it can be
> better than having 2 options, but it will add some workaround to do with
> other platforms as well if we call the opendatabase function, atm it is
> better to let an other option to set the directory from where the db you
> want to copy is.

I do agree that it is better to have one option that is more flexible.
Unfortunately we cannot break the existing options without breaking
existing apps when they are updated with a new version of this plugin. API
changes have to be done very carefully for this reason.

My idea in this case is to add a createFromPath option. We can also add
this option to work _only_ for Android until enough people ask for this to
be supported for iOS as well.

In general, don't worry too much about the branching since I expect to
cherry-pick the changes and may add some minor rework before publishing
them. Again I cannot promise when I will publish your changes so you may
have to maintain your own version in the fork for a while.

**Comment by brody2consult** [comment]
I will integrate these changes (with some rework) when I get a chance. May be in another version such as cordova-sqlite-ext. Closing for now.

**Pull request closed without merging**
