### PR TITLE
Support for browser platform (with WebSQL).

### PR DESCRIPTION
**Pull request by rafw87**
This is a simple implementation of browser platform, using WebSQL.
It doesn't have implementation of .close() and .deleteDatabase(), these methods are calling success() but are doing nothing (except writing warning to log). Due of it, selfTest is passing only once and reguires to clear database manually.
EDIT: second commit implements .deleteDatabase() by deleting all tables - it's enough to fix selfTest.

### CODE REVIEW

**Comment by brody2consult** [comment]
Hi @rafw87 thanks for the contribution. Did you run it against the full test suite?

Looking at the changes I don't think it will pass the error handling tests. Please correct me if I am mistaken somehow. To be honest I was considering a much different approach.

**Comment by rafw87** [comment]
I checked this error handling tests and I see that most of errors are caused by different error messages etc than expected, for example:
Error: Expected 'Cannot read property 'toString' of undefined' to match /Unable to get property 'toString' of undefined or null reference/.

I see that there are different expectations for different environments (Windows, Android, WP8), so maybe it should be done that way for browser platform (expectations like for isWebSql)?

**Comment by rafw87** [comment]
Hi,
I'll check it later today. Both CI jobs passed, I assume that full test suite is something else?

It's possible that some cases are not handled properly. I didn't spend so much time for this platform, it was rather a quick change to have code in my project more clean. I decided to share it "as-is", maybe it will be useful for someone.

Thanks for this plugin:)

<div>-------- Oryginalna wiadomość --------</div><div>Od: Chris Brody notifications@github.com </div><div>Data:25.10.2016  10:21  (GMT+01:00) </div><div>Do: litehelpers/Cordova-sqlite-storage Cordova-sqlite-storage@noreply.github.com </div><div>DW: rafw87 raf_w87@wp.pl, Mention mention@noreply.github.com </div><div>Temat: Re: [litehelpers/Cordova-sqlite-storage] Support for browser platform
  (with WebSQL). (#575) </div><div>
</div>Hi @rafw87 thanks for the contribution. Did you run it against the full test suite?

Looking at the changes I don't think it will pass the error handling tests. Please correct me if I am mistaken somehow. To be honest I was considering a much different approach.

**Comment by brody2consult** [comment]
> Both CI jobs passed, I assume that full test suite is something else?

The CI jobs test the Android and iOS platform implementations. There is no CI for the browser platform since it would be new. (Also there is currently no CI for Windows.)

> I decided to share it "as-is", maybe it will be useful for someone.

Thanks for sharing. It was definitely very interesting to try running it.

I think it will take a very different approach to pass some of the more difficult tests including nested transactions, error handling, and error recovery. I will work on this when I get a chance. Discussion will be continued in #297.

> Thanks for this plugin:)

You are welcome)

**Comment by brody2consult** [comment]
Closing in favor of PR #576

**Pull request closed without merging**
